### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by yale2a1** [yale2a1/NeisBot#3]
```/set <argument> <argument>```  ```args1```, ```args2```
```console
2016-02-01 21:33:17,840 - telegram.dispatcher - ERROR - An uncaught error was raised while processing an update
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/telegram/dispatcher.py", line 180, in start
    self.processUpdate(update)
  File "/usr/local/lib/python3.5/site-packages/telegram/dispatcher.py", line 243, in processUpdate
    self.dispatchTelegramCommand(update)
  File "/usr/local/lib/python3.5/site-packages/telegram/dispatcher.py", line 507, in dispatchTelegramCommand
    self.dispatchTo(self.telegram_command_handlers[command], update)
  File "/usr/local/lib/python3.5/site-packages/telegram/dispatcher.py", line 596, in dispatchTo
    self.call_handler(handler, update, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/telegram/dispatcher.py", line 637, in call_handler
    handler(self.bot, update, **target_kwargs)
TypeError: setting() missing 2 required positional arguments: 'args1' and 'args2'
```

**Comment by yale2a1** [comment]
코드 갈아엎음
